export const BIO101 = [
  { question: 'Powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Golgi apparatus', 'Mitochondria'], answer: 3, explanation: 'Mitochondria produce ATP energy' },
  { question: 'Photosynthesis occurs in?', options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Ribosome'], answer: 2, explanation: 'Chloroplasts contain chlorophyll for photosynthesis' },
  { question: 'Basic unit of life?', options: ['Tissue', 'Organ', 'Cell', 'Atom'], answer: 2, explanation: 'Cell is the basic structural unit of life' },
  { question: 'DNA stands for?', options: ['Deoxyribonucleic Acid', 'Diribonucleic Acid', 'Deoxyribonitric Acid', 'Double Nucleic Acid'], answer: 0, explanation: 'DNA = Deoxyribonucleic Acid' },
  { question: 'Universal blood donor?', options: ['A', 'B', 'AB', 'O'], answer: 3, explanation: 'Blood group O negative donates to all' },
  { question: 'Osmosis is?', options: ['Movement of solute', 'Water from low to high concentration', 'Water from high to low concentration', 'Active transport'], answer: 2, explanation: 'Water moves from high to low concentration through membrane' },
  { question: 'Function of nucleus?', options: ['Energy production', 'Protein synthesis', 'Controls cell and contains DNA', 'Digestion'], answer: 2, explanation: 'Nucleus is control center of the cell' },
  { question: 'Plants absorb which gas in photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2, explanation: 'Plants absorb CO₂ and release O₂' },
  { question: 'Equation for photosynthesis?', options: ['CO₂ + H₂O → glucose + O₂', 'Glucose + O₂ → CO₂ + H₂O', 'H₂O → H₂ + O₂', 'CO₂ → C + O₂'], answer: 0, explanation: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂' },
  { question: 'Water absorbed by plant through?', options: ['Leaves', 'Stem', 'Root hair cells', 'Flowers'], answer: 2, explanation: 'Root hair cells absorb water from soil' },
  { question: 'Function of red blood cells?', options: ['Fight infection', 'Carry oxygen', 'Clot blood', 'Produce antibodies'], answer: 1, explanation: 'RBCs carry oxygen via haemoglobin' },
  { question: 'Mitosis produces?', options: ['4 different cells', '2 identical cells', '4 identical cells', '2 different cells'], answer: 1, explanation: 'Mitosis produces 2 genetically identical daughter cells' },
  { question: 'Role of ribosomes?', options: ['Energy production', 'Protein synthesis', 'DNA replication', 'Cell division'], answer: 1, explanation: 'Ribosomes are sites of protein synthesis' },
  { question: 'Fungi belong to which kingdom?', options: ['Plantae', 'Animalia', 'Fungi', 'Protista'], answer: 2, explanation: 'Fungi form their own kingdom' },
  { question: 'Ecology is the study of?', options: ['Cells', 'Genes', 'Organisms and environment', 'Fossils'], answer: 2, explanation: 'Ecology studies interactions between organisms and environment' },
  { question: 'Function of white blood cells?', options: ['Carry oxygen', 'Clot blood', 'Fight infection', 'Transport nutrients'], answer: 2, explanation: 'WBCs fight infection as part of immune system' },
  { question: 'Largest organ in human body?', options: ['Liver', 'Brain', 'Skin', 'Lungs'], answer: 2, explanation: 'Skin is the largest organ' },
  { question: 'Cells release energy through?', options: ['Photosynthesis', 'Respiration', 'Digestion', 'Excretion'], answer: 1, explanation: 'Cellular respiration releases energy from glucose' },
  { question: 'Controls what enters/exits cell?', options: ['Cell wall', 'Cell membrane', 'Nucleus', 'Vacuole'], answer: 1, explanation: 'Cell membrane is selectively permeable' },
  { question: 'What is a chromosome?', options: ['A type of cell', 'DNA strand carrying genes', 'A protein molecule', 'An organelle'], answer: 1, explanation: 'Chromosomes carry genetic information' },
]
