export const CHE101 = [
  { question: 'Atomic number of Carbon?', options: ['6', '12', '8', '14'], answer: 0, explanation: 'Carbon has 6 protons, atomic number = 6' },
  { question: 'Chemical symbol for Gold?', options: ['Go', 'Gd', 'Au', 'Ag'], answer: 2, explanation: 'Au comes from Latin "Aurum"' },
  { question: 'pH of pure water?', options: ['5', '6', '7', '8'], answer: 2, explanation: 'Pure water is neutral, pH = 7' },
  { question: 'Most abundant gas in atmosphere?', options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'], answer: 2, explanation: 'Nitrogen = 78% of atmosphere' },
  { question: 'Chemical formula for water?', options: ['HO', 'H₂O', 'H₂O₂', 'HO₂'], answer: 1, explanation: '2 hydrogen + 1 oxygen = H₂O' },
  { question: 'Valency of Oxygen?', options: ['1', '2', '3', '4'], answer: 1, explanation: 'Oxygen needs 2 electrons, valency = 2' },
  { question: 'Which is a physical change?', options: ['Burning wood', 'Rusting iron', 'Melting ice', 'Cooking food'], answer: 2, explanation: 'Melting ice changes state, not composition' },
  { question: 'Chemical symbol for Sodium?', options: ['So', 'Sd', 'Na', 'Nm'], answer: 2, explanation: 'Na from Latin "Natrium"' },
  { question: 'Bond type in NaCl?', options: ['Covalent', 'Ionic', 'Metallic', 'Hydrogen'], answer: 1, explanation: 'Na gives electron to Cl = ionic bond' },
  { question: 'Elements in periodic table?', options: ['108', '112', '116', '118'], answer: 3, explanation: 'Modern periodic table has 118 elements' },
  { question: 'Formula for carbon dioxide?', options: ['CO', 'CO₂', 'C₂O', 'C₂O₂'], answer: 1, explanation: '1 carbon + 2 oxygen = CO₂' },
  { question: 'What is an acid?', options: ['Releases OH⁻', 'Releases H⁺', 'Neutral substance', 'Metallic compound'], answer: 1, explanation: 'Acid donates H⁺ ions in solution' },
  { question: 'Atomic mass of Hydrogen?', options: ['1', '2', '4', '8'], answer: 0, explanation: 'Hydrogen atomic mass ≈ 1 amu' },
  { question: 'Definite volume no definite shape?', options: ['Solid', 'Liquid', 'Gas', 'Plasma'], answer: 1, explanation: 'Liquids have fixed volume, take container shape' },
  { question: 'Chemical symbol for Iron?', options: ['Ir', 'In', 'Fe', 'Fr'], answer: 2, explanation: 'Fe from Latin "Ferrum"' },
  { question: 'Oxidation means?', options: ['Gain of electrons', 'Loss of electrons', 'Gain of protons', 'Loss of protons'], answer: 1, explanation: 'OIL: Oxidation Is Loss of electrons' },
  { question: 'Molar mass of H₂O?', options: ['10 g/mol', '16 g/mol', '18 g/mol', '20 g/mol'], answer: 2, explanation: '2(1) + 16 = 18 g/mol' },
  { question: 'Zinc + HCl produces?', options: ['Oxygen', 'Hydrogen', 'Chlorine', 'Nitrogen'], answer: 1, explanation: 'Zn + 2HCl → ZnCl₂ + H₂' },
  { question: 'What is a catalyst?', options: ['Consumed in reaction', 'Speeds reaction without being consumed', 'Product of reaction', 'A reactant'], answer: 1, explanation: 'Catalyst speeds reaction, not consumed' },
  { question: 'Charge of an electron?', options: ['Positive', 'Negative', 'Neutral', 'Variable'], answer: 1, explanation: 'Electrons carry negative charge' },
]
