export const GST101 = [
  { question: 'Which is a conjunction?', options: ['Quickly', 'Beautiful', 'And', 'Run'], answer: 2, explanation: '"And" joins words, phrases or clauses' },
  { question: 'What is a noun?', options: ['Action word', 'Describing word', 'Name of person/place/thing', 'Connecting word'], answer: 2, explanation: 'A noun names a person, place, thing or idea' },
  { question: 'Which is a pronoun?', options: ['Run', 'He', 'Blue', 'Slowly'], answer: 1, explanation: '"He" replaces a noun (male person)' },
  { question: 'Punctuation ending a question?', options: ['.', '!', '?', ','], answer: 2, explanation: 'Questions end with question mark (?)' },
  { question: 'Antonym of "hot"?', options: ['Warm', 'Cold', 'Spicy', 'Boiling'], answer: 1, explanation: 'Antonym = opposite meaning. Cold is opposite of hot' },
  { question: 'Synonym of "happy"?', options: ['Sad', 'Angry', 'Joyful', 'Tired'], answer: 2, explanation: 'Synonym = same meaning. Joyful means happy' },
  { question: 'Correct sentence?', options: ['She don\'t like it', 'She doesn\'t like it', 'She not like it', 'She no like it'], answer: 1, explanation: 'Correct subject-verb agreement for third person singular' },
  { question: 'Plural of "child"?', options: ['Childs', 'Childes', 'Children', 'Childrens'], answer: 2, explanation: '"Children" is the irregular plural of "child"' },
  { question: 'Which word is an adjective?', options: ['Run', 'Quickly', 'Beautiful', 'They'], answer: 2, explanation: '"Beautiful" describes a noun — it is an adjective' },
  { question: 'What is a metaphor?', options: ['Comparison using like/as', 'Direct comparison without like/as', 'An exaggeration', 'A rhyme scheme'], answer: 1, explanation: 'Metaphor: "Life is a journey" — no like/as' },
  { question: 'What is a simile?', options: ['Direct comparison', 'Comparison using like or as', 'A type of noun', 'An action word'], answer: 1, explanation: 'Simile uses "like" or "as": "brave as a lion"' },
  { question: 'Correct spelling?', options: ['Recieve', 'Receive', 'Receve', 'Receeve'], answer: 1, explanation: '"i before e except after c" → Receive' },
  { question: '"I was eating" is which tense?', options: ['Simple past', 'Past continuous', 'Present perfect', 'Future'], answer: 1, explanation: '"Was eating" = past continuous' },
  { question: 'What is a preposition?', options: ['Naming word', 'Word showing relationship', 'Action word', 'Describing word'], answer: 1, explanation: 'Prepositions: in, on, at, by, for, with...' },
  { question: 'Example of alliteration?', options: ['She sells seashells', 'The sun is hot', 'I like reading', 'Books are good'], answer: 0, explanation: 'Alliteration = repeated initial consonant sounds' },
  { question: '"Benevolent" means?', options: ['Evil', 'Generous/kind', 'Angry', 'Confused'], answer: 1, explanation: 'Benevolent = well-meaning and kindly' },
  { question: 'Passive voice sentence?', options: ['The dog bit the man', 'The man was bitten by the dog', 'He runs fast', 'She sings well'], answer: 1, explanation: 'Passive: subject receives the action' },
  { question: 'What is a clause?', options: ['A single word', 'Group of words with subject and verb', 'A punctuation mark', 'A type of sentence'], answer: 1, explanation: 'A clause has a subject and a verb' },
  { question: 'Superlative of "good"?', options: ['Gooder', 'Better', 'Best', 'Most good'], answer: 2, explanation: 'Good → Better → Best (irregular)' },
  { question: '"Ambiguous" means?', options: ['Very clear', 'Open to more than one interpretation', 'Completely wrong', 'Very long'], answer: 1, explanation: 'Ambiguous = unclear or having multiple meanings' },
]
