export const PHY101 = [
  { question: 'SI unit of force?', options: ['Watt', 'Joule', 'Newton', 'Pascal'], answer: 2, explanation: 'Force measured in Newtons (N)' },
  { question: "Newton's first law is called?", options: ['Acceleration', 'Gravity', 'Inertia', 'Motion'], answer: 2, explanation: 'First law = Law of Inertia' },
  { question: 'Speed of light in vacuum?', options: ['3×10⁶ m/s', '3×10⁸ m/s', '3×10¹⁰ m/s', '3×10⁴ m/s'], answer: 1, explanation: 'c = 3×10⁸ m/s' },
  { question: 'Unit of electric current?', options: ['Volt', 'Watt', 'Ampere', 'Ohm'], answer: 2, explanation: 'Current measured in Amperes (A)' },
  { question: 'F = ma is which law?', options: ['First law', 'Second law', 'Third law', 'Gravity'], answer: 1, explanation: "Newton's Second Law: F = ma" },
  { question: 'Unit of resistance?', options: ['Ampere', 'Volt', 'Ohm', 'Watt'], answer: 2, explanation: 'Resistance in Ohms (Ω)' },
  { question: 'Moving car has which energy?', options: ['Potential', 'Kinetic', 'Chemical', 'Nuclear'], answer: 1, explanation: 'Kinetic energy = ½mv²' },
  { question: 'Acceleration due to gravity?', options: ['9.8 m/s', '9.8 m/s²', '10 m/s', '8.9 m/s²'], answer: 1, explanation: 'g ≈ 9.8 m/s²' },
  { question: 'Unit of power?', options: ['Joule', 'Newton', 'Watt', 'Pascal'], answer: 2, explanation: 'Power in Watts (W)' },
  { question: "Ohm's law?", options: ['V = IR', 'P = IV', 'F = ma', 'E = mc²'], answer: 0, explanation: 'V = IR' },
  { question: 'Unit of frequency?', options: ['Watt', 'Hertz', 'Newton', 'Joule'], answer: 1, explanation: 'Frequency in Hertz (Hz)' },
  { question: 'Ships float due to?', options: ["Pascal's principle", "Archimedes' principle", "Bernoulli's principle", "Newton's principle"], answer: 1, explanation: "Archimedes' principle explains buoyancy" },
  { question: 'Formula for KE?', options: ['KE = mv', 'KE = ½mv²', 'KE = mgh', 'KE = mv²'], answer: 1, explanation: 'KE = ½mv²' },
  { question: 'Formula for PE?', options: ['PE = ½mv²', 'PE = mgh', 'PE = Fd', 'PE = mv'], answer: 1, explanation: 'PE = mgh' },
  { question: 'Sound is what type of wave?', options: ['Transverse', 'Electromagnetic', 'Longitudinal', 'Surface'], answer: 2, explanation: 'Sound is a longitudinal wave' },
  { question: 'Unit of pressure?', options: ['Newton', 'Pascal', 'Watt', 'Joule'], answer: 1, explanation: 'Pressure in Pascals (Pa)' },
  { question: 'Longest wavelength in visible light?', options: ['Violet', 'Blue', 'Green', 'Red'], answer: 3, explanation: 'Red has longest wavelength ~700nm' },
  { question: 'Formula for work done?', options: ['W = F/d', 'W = Fd', 'W = F+d', 'W = F×t'], answer: 1, explanation: 'W = Fd' },
  { question: 'Absolute zero in Celsius?', options: ['-100°C', '-200°C', '-273°C', '-373°C'], answer: 2, explanation: 'Absolute zero = -273.15°C' },
  { question: 'Bending of light is called?', options: ['Reflection', 'Refraction', 'Diffraction', 'Dispersion'], answer: 1, explanation: 'Refraction is bending of light' },
]
